import pathlib
import sys
import time
from collections import defaultdict


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
INGREDIENTS_DIR = REPO_ROOT / "Rules/Ruleset/Active/AdBlock"
BUILD_TARGETS = {
    "adblock": {
        "inputs": [
            "BanAD.list",
            "BanEasyList.list",
            "BanEasyListChina.list",
            "BanProgramAD.list",
        ],
        "output": REPO_ROOT / "Rules/Outputs/MergedADBan.list",
        "title": "ACL4SSR-Neo Merged AD Block List",
    },
    "privacy": {
        "inputs": ["BanEasyPrivacy.list"],
        "output": REPO_ROOT / "Rules/Outputs/MergedPrivacy.list",
        "title": "ACL4SSR-Neo Merged Privacy List",
    },
}


def log(message):
    print(f"[*] {message}", flush=True)


def parse_rule(line):
    """Return a normalized rule tuple while preserving optional modifiers."""
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None

    parts = tuple(part.strip() for part in stripped.split(","))
    if len(parts) < 2 or not parts[0] or not parts[1]:
        raise ValueError(f"Malformed rule: {stripped}")
    return (parts[0].upper(), *parts[1:])


def resolve_domain_conflicts(rules):
    """Drop an exact DOMAIN when an equivalent DOMAIN-SUFFIX is present.

    DOMAIN-SUFFIX covers both the named domain and its subdomains. Other rule
    type combinations are retained because their semantics are not equivalent.
    """
    by_value = defaultdict(set)
    for rule in rules:
        by_value[rule[1]].add(rule[0])

    resolved = set(rules)
    conflicts = []
    for value, rule_types in by_value.items():
        if {"DOMAIN", "DOMAIN-SUFFIX"}.issubset(rule_types):
            removed = {rule for rule in resolved if rule[0] == "DOMAIN" and rule[1] == value}
            resolved.difference_update(removed)
            conflicts.append((value, "DOMAIN-SUFFIX", "DOMAIN"))
    return resolved, conflicts


def render_output(title, rules, conflict_count):
    lines = [
        "# --------------------------------------------------------------",
        f"# {title}",
        "# Generated by ACL4SSR-Neo Smart Build System",
        f"# Total Rules: {len(rules)}",
        f"# Conflicts Resolved: {conflict_count}",
        "# --------------------------------------------------------------",
        "",
    ]
    lines.extend(",".join(rule) for rule in sorted(rules))
    return "\n".join(lines) + "\n"


def build_target(target_name, config, ingredients_dir=INGREDIENTS_DIR):
    rules = set()
    raw_count = 0

    for filename in config["inputs"]:
        path = ingredients_dir / filename
        if not path.is_file():
            raise FileNotFoundError(f"Missing ingredient for {target_name}: {path}")

        log(f"[{target_name}] Reading ingredient: {filename}")
        for line in path.read_text(encoding="utf-8").splitlines():
            parsed = parse_rule(line)
            if parsed:
                raw_count += 1
                rules.add(parsed)

    resolved, conflicts = resolve_domain_conflicts(rules)
    output = render_output(config["title"], resolved, len(conflicts))
    output_path = config["output"]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8")

    log(
        f"[{target_name}] Ingested {raw_count} effective lines; "
        f"wrote {len(resolved)} unique rules and resolved {len(conflicts)} conflict(s)."
    )
    for value, kept, removed in conflicts[:5]:
        log(f"[{target_name}] {value}: kept {kept}, removed narrower {removed}")


def build():
    log("Starting Smart Build System...")
    started = time.monotonic()
    if not INGREDIENTS_DIR.is_dir():
        raise FileNotFoundError(f"Ingredient directory not found: {INGREDIENTS_DIR}")

    for target_name, config in BUILD_TARGETS.items():
        build_target(target_name, config)
    log(f"Build completed in {time.monotonic() - started:.2f} seconds.")


if __name__ == "__main__":
    try:
        build()
    except Exception as error:
        log(f"Fatal Error: {error}")
        sys.exit(1)
